import AddRoundedIcon from '@mui/icons-material/AddRounded'
import AssignmentIndOutlinedIcon from '@mui/icons-material/AssignmentIndOutlined'
import CalendarTodayOutlinedIcon from '@mui/icons-material/CalendarTodayOutlined'
import ChecklistOutlinedIcon from '@mui/icons-material/ChecklistOutlined'
import ChevronLeftRoundedIcon from '@mui/icons-material/ChevronLeftRounded'
import ChevronRightRoundedIcon from '@mui/icons-material/ChevronRightRounded'
import ExpandMoreRoundedIcon from '@mui/icons-material/ExpandMoreRounded'
import PendingActionsOutlinedIcon from '@mui/icons-material/PendingActionsOutlined'
import RestartAltRoundedIcon from '@mui/icons-material/RestartAltRounded'
import SearchRoundedIcon from '@mui/icons-material/SearchRounded'
import TaskAltRoundedIcon from '@mui/icons-material/TaskAltRounded'
import { useEffect, useMemo, useState } from 'react'
import '../styles/checklist.css'
import {
  getStoredChecklistManagementRecords,
  saveChecklistManagementRecords,
} from '../utils/checklistStatusStorage'

const MANAGERS = ['이안전', '김안전', '박점검', '최점검']
const rows = [
  ['비상구 피난 통로 점검','시설 안전','A동 1층 복도','매일','이안전','','2026-07-10 09:00','점검 대기'],['소화기 및 소방설비 점검','화재 예방','A동 2층 복도','매주','김안전','최점검','2026-07-11 14:00','조치 대기'],['운반 장비 방호설비 점검','작업 안전','A동 5층 작업장','매월','','','2026-07-12 10:00','점검 대기'],['전기 분전반 및 차단기 점검','시설 안전','C동 지하 1층','매월','최점검','이안전','2026-07-13 11:00','조치 완료'],['보호구 착용 상태 점검','작업 안전','B동 3층 작업장','매일','박점검','','2026-07-14 13:00','점검 완료'],['적재물 전도 위험 점검','시설 안전','C동 창고','매주','이안전','김안전','2026-07-15 15:00','조치 대기'],['비상 조명 및 유도등 점검','화재 예방','A동 3층 계단','매월','','','2026-07-16 10:00','점검 대기'],['가스 차단 밸브 점검','시설 안전','식당 조리실','매주','최점검','김안전','2026-07-17 08:30','조치 완료'],['방화문 폐쇄 상태 점검','화재 예방','B동 2층 복도','매일','이안전','','2026-07-18 09:30','점검 대기'],['비상 방송 설비 점검','화재 예방','A동 안내실','매주','김안전','','2026-07-19 11:00','점검 대기'],['작업장 바닥 미끄럼 점검','작업 안전','B동 1층 포장실','매일','박점검','최점검','2026-07-20 16:00','조치 대기'],['산업용 배터리 보관 점검','시설 안전','C동 충전실','매월','최점검','이안전','2026-07-21 13:30','조치 완료'],['하역장 안전 난간 점검','작업 안전','A동 하역장','매월','이안전','박점검','2026-07-22 07:30','조치 완료'],['환기 설비 필터 점검','시설 안전','B동 지하 기계실','매월','','','2026-07-23 10:00','점검 대기'],['휴게실 소화 설비 점검','화재 예방','C동 휴게실','매주','김안전','박점검','2026-07-24 12:00','조치 완료'],['지게차 충전 구역 점검','작업 안전','B동 1층 충전 구역','매일','박점검','','2026-07-25 17:00','점검 대기'],
]
export const CHECKLIST_MANAGEMENT_MOCK_RECORDS = rows.map(([name,category,location,cycle,inspectionAssignee,actionAssignee,dateTime,progress], index) => ({ id:index+1,name,category,location,cycle,inspectionAssignee,actionAssignee,dateTime,progress }))
const rangeText = (monthValue) => { const [year, month] = monthValue.split('-').map(Number); return `${year}. ${String(month).padStart(2,'0')}. 01 - ${year}. ${String(month).padStart(2,'0')}. ${new Date(year, month, 0).getDate()}` }
const getInitialRecords = () => {
  const stored = getStoredChecklistManagementRecords().filter((item) => (
    item.source === 'board' || item.source === 'checklist-action'
  ))
  const storedIds = new Set(stored.map((item) => String(item.id)))
  return [...stored, ...CHECKLIST_MANAGEMENT_MOCK_RECORDS.filter((item) => !storedIds.has(String(item.id)))]
}
const isInspectionRecord = (item) => item.type === 'inspection' || (!item.type && item.progress.startsWith('점검'))

function ChecklistManagementPage() {
  const [records, setRecords] = useState(() => getInitialRecords())
  const [filters, setFilters] = useState({ query:'', category:'분류', inspection:'점검 담당자', action:'조치 담당자', status:'진행 상태' })
  const [periodMonth, setPeriodMonth] = useState('2026-07')
  const [usePeriod, setUsePeriod] = useState(false)
  const [isDateOpen, setIsDateOpen] = useState(false)
  const [page, setPage] = useState(0)
  const [selected, setSelected] = useState([])
  const [detailItem, setDetailItem] = useState(null)
  const [isCreateOpen, setIsCreateOpen] = useState(false)
  const [assignmentMode, setAssignmentMode] = useState(null)
  const [memberQuery, setMemberQuery] = useState('')
  useEffect(() => { const syncRecords = () => setRecords(getInitialRecords()); window.addEventListener('focus', syncRecords); window.addEventListener('storage', syncRecords); return () => { window.removeEventListener('focus', syncRecords); window.removeEventListener('storage', syncRecords) } }, [])
  const changeFilter = (key, value) => { setFilters((current) => ({ ...current, [key]:value })); setPage(0) }
  const filtered = useMemo(() => records.filter((item) => (!filters.query || item.name.includes(filters.query) || item.location.includes(filters.query)) && (filters.category === '분류' || item.category === filters.category) && (filters.inspection === '점검 담당자' || item.inspectionAssignee === filters.inspection) && (filters.action === '조치 담당자' || item.actionAssignee === filters.action) && (filters.status === '진행 상태' || item.progress === filters.status) && (!usePeriod || item.dateTime.startsWith(periodMonth))), [records, filters, periodMonth, usePeriod])
  const pageCount = Math.max(1, Math.ceil(filtered.length / 8)); const active = Math.min(page, pageCount - 1); const visible = filtered.slice(active * 8, active * 8 + 8)
  const chosen = records.filter((item) => selected.includes(item.id)); const actionEnabled = chosen.length > 0 && chosen.every((item) => item.progress === '조치 대기')
  const stats = [['전체 체크리스트', records.length, '등록된 기준 항목', ChecklistOutlinedIcon],['점검 대기', records.filter((item) => item.progress === '점검 대기').length, '점검 진행이 필요해요', PendingActionsOutlinedIcon],['조치 대기', records.filter((item) => item.progress === '조치 대기').length, '조치 등록이 필요해요', PendingActionsOutlinedIcon],['담당자 미배정', records.filter((item) => !item.inspectionAssignee).length, '빠른 배정이 필요해요', TaskAltRoundedIcon]]
  const toggle = (id) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current,id])
  const reset = () => { setFilters({ query:'', category:'분류', inspection:'점검 담당자', action:'조치 담당자', status:'진행 상태' }); setPeriodMonth('2026-07'); setUsePeriod(false); setPage(0) }
  const addItem = (item) => { setRecords((current) => { const next = [{ ...item, id: Date.now() }, ...current]; saveChecklistManagementRecords(next); return next }); setIsCreateOpen(false); setPage(0) }
  const updateCycle = (id, cycle) => {
    setRecords((current) => {
      const next = current.map((item) => item.id === id ? { ...item, cycle } : item)
      saveChecklistManagementRecords(next)
      return next
    })
    setDetailItem((current) => current?.id === id ? { ...current, cycle } : current)
  }
  const assignMember = (member) => { const field = assignmentMode === 'inspection' ? 'inspectionAssignee' : 'actionAssignee'; setRecords((current) => { const next = current.map((item) => selected.includes(item.id) ? { ...item, [field]: member } : item); saveChecklistManagementRecords(next); return next }); setSelected([]); setMemberQuery(''); setAssignmentMode(null) }
  const members = MANAGERS.filter((member) => member.includes(memberQuery.trim()))
  return <section className="checklist-management-page">
    <div className="checklist-metrics">{stats.map(([label,value,note,Icon], index) => <article className={`checklist-metric metric-${index}`} key={label}><span className="metric-heading"><i><Icon /></i>{label}</span><strong>{value}<small>건</small></strong><p>{note}</p></article>)}</div>
    <article className="management-table-card"><div className="management-table-header"><div><span className="section-kicker">CHECKLIST OVERVIEW</span><h3>전체 체크리스트</h3><p>일시를 확인하고 점검·조치 담당자를 배정합니다.</p></div><div className="management-header-actions"><button className="checklist-create-button" type="button" onClick={() => setIsCreateOpen(true)}><AddRoundedIcon /> 항목 추가</button><div className="date-filter"><button type="button" onClick={() => setIsDateOpen((open) => !open)}><CalendarTodayOutlinedIcon /><span>{rangeText(periodMonth)}</span></button>{isDateOpen && <div className="date-filter-menu"><label>조회 월<input type="month" value={periodMonth} onChange={(event) => { setPeriodMonth(event.target.value); setUsePeriod(true); setPage(0); setIsDateOpen(false) }} /></label></div>}</div></div></div>
    <div className="management-filters"><label className="management-search"><SearchRoundedIcon /><input value={filters.query} onChange={(event) => changeFilter('query', event.target.value)} placeholder="점검 이름 또는 구역 검색" /></label><Filter value={filters.category} onChange={(value) => changeFilter('category',value)} options={['분류','시설 안전','화재 예방','작업 안전']} /><Filter value={filters.inspection} onChange={(value) => changeFilter('inspection',value)} options={['점검 담당자',...MANAGERS]} /><Filter value={filters.action} onChange={(value) => changeFilter('action',value)} options={['조치 담당자',...MANAGERS]} /><Filter value={filters.status} onChange={(value) => changeFilter('status',value)} options={['진행 상태','점검 대기','점검 완료','조치 대기','조치 완료']} /><button className="filter-reset" type="button" onClick={reset}><RestartAltRoundedIcon /> 초기화</button></div>
    <div className="bulk-assign-toolbar"><span>선택 <strong>{selected.length}</strong>건</span><div><button type="button" disabled={!chosen.length} onClick={() => setAssignmentMode('inspection')}><AssignmentIndOutlinedIcon /> 점검 담당자 배정</button><button type="button" disabled={!actionEnabled} onClick={() => setAssignmentMode('action')}><AssignmentIndOutlinedIcon /> 조치 담당자 배정</button></div></div>
    <div className="checklist-table-wrap"><table className="checklist-management-table master-checklist-table"><thead><tr><th className="checklist-select-col"><input type="checkbox" checked={visible.length > 0 && visible.every((item) => selected.includes(item.id))} onChange={(event) => setSelected((current) => event.target.checked ? [...new Set([...current,...visible.map((item) => item.id)])] : current.filter((id) => !visible.some((item) => item.id === id)))} /></th><th>점검 이름</th><th>적용 구역</th><th>점검 담당자</th><th>조치 담당자</th><th>일시</th><th>진행 상태</th></tr></thead><tbody>{visible.map((item) => <tr className="checklist-detail-row" key={item.id} onClick={() => setDetailItem(item)}><td className="checklist-select-col"><input type="checkbox" checked={selected.includes(item.id)} onClick={(event) => event.stopPropagation()} onChange={() => toggle(item.id)} /></td><td><strong>{item.name}</strong><span className="table-category">{item.category}</span></td><td><span className="location-cell">{item.location}</span></td><td><Assignee value={item.inspectionAssignee} /></td><td><Assignee value={item.progress.startsWith('점검') ? '' : item.actionAssignee} /></td><td>{item.dateTime}</td><td><Status value={item.progress} /></td></tr>)}</tbody></table></div>
    <footer className="checklist-pagination"><span>총 <strong>{filtered.length}</strong>건</span><div><button type="button" disabled={active === 0} onClick={() => setPage((current) => current - 1)}><ChevronLeftRoundedIcon /></button><b>{active + 1} / {pageCount}</b><button type="button" disabled={active === pageCount - 1} onClick={() => setPage((current) => current + 1)}><ChevronRightRoundedIcon /></button></div></footer></article>{detailItem && <ChecklistDetailModal item={detailItem} onCycleChange={updateCycle} onClose={() => setDetailItem(null)} />}{isCreateOpen && <CreateModal onClose={() => setIsCreateOpen(false)} onCreate={addItem} />}{assignmentMode && <AssignmentModal mode={assignmentMode} count={selected.length} members={members} query={memberQuery} onQueryChange={setMemberQuery} onAssign={assignMember} onClose={() => { setMemberQuery(''); setAssignmentMode(null) }} />}</section>
}
function Filter({ value, options, onChange }) { const [isOpen, setIsOpen] = useState(false); return <div className={`management-filter-select${isOpen ? ' is-open' : ''}`}><button type="button" onClick={() => setIsOpen((open) => !open)}><span>{value}</span><ExpandMoreRoundedIcon /></button>{isOpen && <div className="management-select-menu">{options.map((option) => <button type="button" className={option === value ? 'is-selected' : ''} key={option} onClick={() => { onChange(option); setIsOpen(false) }}>{option}{option === value && <span>✓</span>}</button>)}</div>}</div> }
function Assignee({ value }) { if (!value) return <span className="no-photo">미배정</span>; if (value === '게시판') return <span className="assignee-cell is-board-source"><i>게시판</i></span>; return <span className="assignee-cell"><i>{value[0]}</i>{value}</span> }
function Status({ value }) { return <span className={`checklist-status ${value.endsWith('완료') ? 'is-complete' : value === '조치 대기' ? 'is-pending' : 'is-progress'}`}>{value}</span> }
function ChecklistDetailModal({ item, onCycleChange, onClose }) {
  const locations = item.location.split(',').map((location) => location.trim()).filter(Boolean)
  const isInspection = isInspectionRecord(item)
  const inspectionHistory = [{ date:item.dateTime, location:item.location, manager:item.inspectionAssignee || '미배정', status:item.progress.startsWith('점검') ? item.progress : '점검 완료' },{ date:'2026-07-24 09:10', location:item.location, manager:item.inspectionAssignee || '미배정', status:'점검 완료' }]
  const actionHistory = item.progress.startsWith('조치') ? [{ date:item.dateTime, manager:item.actionAssignee || '미배정', status:item.progress }] : []

  return <div className="assignment-modal-backdrop" onMouseDown={onClose}><section className="checklist-detail-modal master-detail-modal" onMouseDown={(event) => event.stopPropagation()}><header><div><span>CHECKLIST DETAIL</span><h3>{item.name}</h3><p>{isInspection ? `${item.category} · ${item.cycle} 점검` : `${item.category} · 조치 항목`}</p></div><button type="button" aria-label="닫기" onClick={onClose}>×</button></header><div className="master-detail-body"><section className="master-summary-grid">{isInspection && <div><span>점검 주기</span><select className="detail-cycle-select" aria-label="점검 주기" value={item.cycle} onChange={(event) => onCycleChange(item.id, event.target.value)}><option>매일</option><option>매주</option><option>매월</option></select></div>}<div><span>일시</span><strong>{item.dateTime}</strong></div><div><span>점검 담당자</span><strong>{item.inspectionAssignee || '미배정'}</strong></div><div><span>진행 상태</span><Status value={item.progress} /></div></section><section><div className="master-section-heading"><h4>적용 구역</h4><span>{locations.length}곳</span></div><div className="master-location-list">{locations.map((location) => <span key={location}>{location}</span>)}</div></section><section><div className="master-section-heading"><h4>점검 이력</h4><span>최근 {inspectionHistory.length}건</span></div><div className="master-history-list">{inspectionHistory.map((entry, index) => <div key={`${entry.date}-${index}`}><span>{entry.date}</span><strong>{entry.location}</strong><span>{entry.manager}</span><Status value={entry.status} /></div>)}</div></section><section><div className="master-section-heading"><h4>조치 이력</h4><span>{actionHistory.length}건</span></div>{actionHistory.length ? <div className="master-history-list">{actionHistory.map((entry) => <div key={entry.date}><span>{entry.date}</span><strong>{entry.manager}</strong><span>조치 담당자</span><Status value={entry.status} /></div>)}</div> : <div className="checklist-empty">등록된 조치 이력이 없습니다.</div>}</section></div><footer><span>점검 및 조치 진행 내역을 확인합니다.</span><button type="button" onClick={onClose}>닫기</button></footer></section></div>
}
function AssignmentModal({ mode, count, members, query, onQueryChange, onAssign, onClose }) { const title = mode === 'inspection' ? '점검 담당자 배정' : '조치 담당자 배정'; return <div className="assignment-modal-backdrop" onMouseDown={onClose}><section className="assignment-modal" onMouseDown={(event) => event.stopPropagation()}><header><div><span>ASSIGNMENT</span><h3>{title}</h3><p>선택한 {count}개 항목에 담당자를 일괄 배정합니다.</p></div><button type="button" aria-label="닫기" onClick={onClose}>×</button></header><div className="assignment-member-section"><div className="assignment-section-heading"><div><span>MANAGER LIST</span><h4>담당자 선택</h4></div><label><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="이름 검색" /></label></div><div className="assignment-member-list">{members.map((member) => <button type="button" className="assignment-member" key={member} onClick={() => onAssign(member)}><span className="member-avatar">{member[0]}</span><span className="member-copy"><strong>{member}</strong><small>현장 담당자</small></span><span className="member-availability is-available">배정</span></button>)}{!members.length && <p className="member-empty">검색 결과가 없습니다.</p>}</div></div><footer><span>담당자를 선택하면 즉시 배정됩니다.</span><button type="button" onClick={onClose}>닫기</button></footer></section></div> }
function CreateModal({ onClose, onCreate }) { const [type, setType] = useState('inspection'); const [form, setForm] = useState({ name:'', location:'', category:'시설 안전', cycle:'매일', dateTime:'2026-07-25T09:00' }); const update = (key, value) => setForm((current) => ({ ...current, [key]: value })); const submit = (event) => { event.preventDefault(); if (!form.name.trim() || !form.location.trim()) return; onCreate({ ...form, type, cycle:type === 'inspection' ? form.cycle : null, name:form.name.trim(), location:form.location.trim(), inspectionAssignee:'', actionAssignee:'', progress:type === 'inspection' ? '점검 대기' : '조치 대기' }) }; return <div className="assignment-modal-backdrop" onMouseDown={onClose}><section className="assignment-modal checklist-create-modal" onMouseDown={(event) => event.stopPropagation()}><header><div><span>ITEM CREATE</span><h3>{type === 'inspection' ? '점검 항목 추가' : '조치 항목 추가'}</h3><p>전체 체크리스트에 새 항목을 등록합니다.</p></div><button type="button" onClick={onClose}>×</button></header><form className="checklist-create-form" onSubmit={submit}><div className="item-type-toggle"><button className={type === 'inspection' ? 'is-active' : ''} type="button" onClick={() => setType('inspection')}>점검 항목</button><button className={type === 'action' ? 'is-active' : ''} type="button" onClick={() => setType('action')}>조치 항목</button></div><label className="is-wide"><span>{type === 'inspection' ? '점검 이름' : '조치 이름'}</span><input value={form.name} onChange={(event) => update('name', event.target.value)} placeholder={type === 'inspection' ? '예: 비상구 피난 통로 점검' : '예: 소화기 압력 게이지 교체'} /></label><label><span>분류</span><select value={form.category} onChange={(event) => update('category', event.target.value)}><option>시설 안전</option><option>화재 예방</option><option>작업 안전</option></select></label>{type === 'inspection' && <label><span>점검 주기</span><select value={form.cycle} onChange={(event) => update('cycle', event.target.value)}><option>매일</option><option>매주</option><option>매월</option></select></label>}<label className="is-wide"><span>적용 구역</span><input value={form.location} onChange={(event) => update('location', event.target.value)} placeholder="여러 구역은 쉼표(,)로 구분하세요" /></label><label><span>일시</span><input type="datetime-local" value={form.dateTime} onChange={(event) => update('dateTime', event.target.value)} /></label><footer><span>{type === 'inspection' ? '점검 대기 상태로 등록됩니다.' : '조치 대기 상태로 등록됩니다.'}</span><div><button type="button" onClick={onClose}>취소</button><button type="submit">등록</button></div></footer></form></section></div> }
export default ChecklistManagementPage
