// Static UI copy only. API/user-entered data must not be added here.
export const en = {
  common: {
    '전체': 'All', '닫기': 'Close', '이전': 'Previous', '다음': 'Next', '검색': 'Search', '초기화': 'Reset', '건': '',
    '등록': 'Registered', '접수': 'Received', '완료': 'Completed', '상태': 'Status', '위험도': 'Risk level',
    '제목': 'Title', '카테고리': 'Category', '장소': 'Location', '번호': 'No.',
    '총': 'Total', '장': ' photos', '이름': 'Name', '위치': 'Location', '유형': 'Type', '시간': 'Time', '담당자': 'Assignee',
    '내용': 'Details', '진행 상황': 'Progress', '위험도 카테고리': 'Risk category', '점검 담당자': 'Inspector',
    '점검 대기': 'Inspection pending', '점검 완료': 'Inspection complete', '조치 대기': 'Action pending', '조치 완료': 'Action complete',
    '점검 목록': 'Inspection list', '조치 목록': 'Action list', '전체 진행률': 'Overall progress', '미분류': 'Uncategorized',
    '시설 안전': 'Facility safety', '소방 안전': 'Fire safety', '정기 점검': 'Regular inspection',
    '로그아웃': 'Log out',
  },
  dashboard: {
    '점검 대기 건수': 'Pending inspections', '점검 완료 건수': 'Completed inspections', '미완료 조치 항목': 'Incomplete actions', '완료된 조치 항목': 'Completed actions',
    '최근 이상 발생 리스트': 'Recent incidents', '홈 요약 지표': 'Home summary', '교육 이수 페이지로 이동': 'Go to learning progress',
    '대상자별 이수 인원을 확인합니다.': 'View completion counts by audience.', '위험도 관리': 'Risk management',
    '전체 위험도 통계와 유형별 위험도 분포를 확인합니다.': 'View overall risk statistics and the distribution by type.',
    '조치 이력 페이지로 이동': 'Go to action history', '기간별 통계량': 'Statistics by period',
    '기간별 위험 발생 추이와 위험 유형 비율을 확인합니다.': 'View incident trends and risk-type ratios by period.',
    '전체 위험도 통계': 'Overall risk statistics', '위험도 페이지로 이동': 'Go to risk management', '유형별 위험도 분포': 'Risk distribution by type',
    '총 감지': 'Total detected', '위험 발생 추이': 'Incident trend', '발생 건수': 'Incidents', '위험 유형 비율': 'Risk type ratio',
    '위험도 관리 항목의 구성 비율입니다.': 'Distribution of risk-management items.', '위험 유형': 'Risk type',
    '소방안전': 'Fire safety', '시설안전': 'Facility safety', '산업안전': 'Industrial safety', '기타': 'Other',
    '화재 발생': 'Fire incident', '적재물': 'Stored materials', '연기': 'Smoke', '안전 수칙 위반': 'Safety-rule violation',
    '상': 'High', '중': 'Medium', '하': 'Low',
    '기간 선택': 'Select period', '최근 7일': 'Last 7 days', '이번 달': 'This month', '지난 달': 'Last month', '직접 설정': 'Custom range', '시작일': 'Start date', '종료일': 'End date', '적용': 'Apply',
  },
  checklist: {
    '점검 · 조치 목록': 'Inspection & Action List', '점검 결과를 확인하고 조치가 필요한 건을 등록하세요.': 'Review inspection results and register actions that are needed.',
    '점검 및 조치 목록 전환': 'Switch inspection and action list', '등록된 조치 항목이 없습니다.': 'There are no registered action items.',
    '완료/조치 등록': 'Complete / Register Action', '점검 이력에서 조치가 필요한 항목을 선택해 조치 업무로 등록합니다.': 'Select an inspection item that needs action and register it as an action task.',
    '등록된 내용이 없습니다.': 'No details have been entered.', '이 점검 건은 이미 조치 목록에 등록되어 있습니다.': 'This inspection is already registered in the action list.',
    '완료된 점검 항목입니다.': 'This inspection item is complete.', '점검자 메모': 'Inspector memo', '점검 결과 또는 필요한 조치 내용을 입력하세요.': 'Enter the inspection result or required action.',
    '조치 필요': 'Action required', '조치내용': 'Action details', '점검 이력이 연결된 조치 업무입니다.': 'This action task is linked to an inspection record.',
    '점검내용': 'Inspection details', '점검 시 입력한 내용이 없습니다.': 'No details were entered during the inspection.',
    '수행한 조치 내용을 입력하세요.': 'Enter the action you performed.', '조치완료 사진': 'Completed-action photos', '등록된 사진이 없습니다.': 'There are no registered photos.',
    '사진 첨부': 'Attach photos', '조치완료': 'Complete action', '목록에서 항목을 선택해 주세요.': 'Select an item from the list.',
    '일시를 확인하고 점검·조치 담당자를 배정합니다.': 'Review schedules and assign inspection or action staff.', '항목 추가': 'Add item',
    '항목 유형': 'Item type', '점검': 'Inspection', '조치': 'Action', '점검 이름, 구역, 담당자 검색': 'Search inspection name, area, or assignee',
    '점검 예정일': 'Scheduled inspection date', '선택': 'Selected', '점검 담당자 배정': 'Assign inspector', '조치 담당자 배정': 'Assign action staff',
    '오늘': 'Today', '내일': 'Tomorrow', '+2일': '+2 days', '분류': 'Category', '진행 상태': 'Status',
    '점검 이름': 'Inspection name', '적용 구역': 'Areas', '타입': 'Type', '조치 담당자': 'Action staff', '일시': 'Schedule',
    '미배정': 'Unassigned', '게시판': 'Board',
  },
  mypage: {
    '계정 설정': 'Account settings', '계정 정보와 보안 설정을 관리할 수 있습니다.': 'Manage your account information and security settings.',
    '계정 설정 메뉴': 'Account settings menu', '비밀번호 변경': 'Change password', '회원탈퇴': 'Delete account',
    '안전을 위해 현재 비밀번호를 확인한 뒤 새 비밀번호로 변경합니다.': 'Verify your current password before setting a new one.',
    '현재 비밀번호': 'Current password', '현재 비밀번호를 입력하세요': 'Enter your current password', '새 비밀번호': 'New password',
    '새 비밀번호를 입력하세요': 'Enter a new password', '새 비밀번호 확인': 'Confirm new password', '새 비밀번호를 한 번 더 입력하세요': 'Enter the new password again',
    '변경 중…': 'Changing…', '회원 탈퇴가 완료되었습니다.': 'Your account has been deleted.',
    '안전하게 로그아웃 처리한 뒤 로그인 화면으로 이동합니다.': 'You will be signed out and redirected to the login page.',
    '탈퇴 전 확인해 주세요': 'Please review before deleting your account', '현재 비밀번호가 일치하지 않습니다. 다시 확인해 주세요.': 'The current password does not match. Please try again.',
    '회원 탈퇴가 완료되면 계정은 즉시 삭제되며, 같은 계정으로 다시 로그인하거나 복구할 수 없습니다.': 'When account deletion is complete, the account is removed immediately and cannot be restored.',
    '계정에 저장된 로그인 정보와 개인 설정이 삭제됩니다.': 'Saved login information and personal settings will be deleted.',
    '작성한 게시글·보고서·점검 이력 등 업무 기록은 작성자 정보 없이 유지될 수 있습니다.': 'Work records such as posts, reports, and inspection history may remain without author information.',
    '계속 이용할 계획이라면 탈퇴 대신 비밀번호 변경을 이용해 주세요.': 'If you plan to continue using the service, change your password instead.',
    '탈퇴 시 계정을 복구할 수 없음을 확인했습니다.': 'I understand that this account cannot be restored after deletion.', '탈퇴 처리 중…': 'Deleting…', '회원 탈퇴': 'Delete account',
  },
  layout: {
    '홈': 'Home', 'CCTV 모니터링': 'CCTV Monitoring', '체크리스트': 'Checklists', '오늘의 할일': "Today's Tasks",
    '담당자 배정': 'Assignments', '정기 점검 목록': 'Inspection List', '이력 관리': 'History',
    '점검/조치 관리': 'Inspection & Actions', '위험도 관리': 'Risk Management', '안전 교육': 'Safety Education',
    '교육 이수': 'My Learning', '교육 관리': 'Education Management', '보고서': 'Reports',
    '위험 신고 게시판': 'Risk Report Board', 'AI 비서': 'AI Assistant', '마이페이지': 'My Page',
  },
  board: {
    '전체신고': 'All reports', '위험 신고하기': 'Report a risk', '선택': 'Selected', '위험도 전체': 'All risk levels',
    '제목, 내용, 장소 검색': 'Search title, content, or location', '신고자': 'Reporter', '신고일': 'Reported on',
    '높음': 'High', '보통': 'Medium', '낮음': 'Low', '익명': 'Anonymous', '접수 중...': 'Receiving...',
    '소방안전': 'Fire safety', '시설안전': 'Facility safety', '산업안전': 'Industrial safety', '기타': 'Other',
    '위험 신고 현황': 'Risk report summary', '위험신고 게시판': 'Risk Report Board',
  },
  education: {
    '이번 주 마감': 'Due This Week', '마감 전 교육을 확인하세요': 'Review courses before their due date.',
    '진행 중': 'In Progress', '수강 중인 교육이 있습니다': 'You have courses in progress.', '이수 완료': 'Completed',
    '완료한 교육을 확인하세요': 'Review completed courses.', '필수 교육': 'Required Training', '정기 교육': 'Recurring Training',
    '내 교육 리스트': 'My Learning List', '교육 이수 현황': 'Learning Progress', '교육명': 'Course', '마감일': 'Due date',
    '안전관리자': 'Safety manager', '관제사': 'Control room operator', '현장관리자': 'Field manager', '일반유저': 'General user',
  },
}

// Compatibility entries kept in the resource during staged screen migration.
// They remain static UI copy and are intentionally not API/user data.
export const shared = {
  '오늘의 안전 현황과 조치 상태를 확인하세요.': "Review today's safety status and actions.",
  '현장 CCTV와 실시간 감지 상태를 확인하세요.': 'Monitor site CCTV and real-time detection status.',
  '오늘 확인할 안전 점검 항목과 조치 상태를 살펴보세요.': "Review today's safety inspection items and action status.",
  '현장별 체크리스트를 확인하고 담당자를 배정하세요.': 'Review site checklists and assign responsible staff.',
  '주기적으로 확인해야 할 주요 점검 항목을 한눈에 살펴보세요.': 'View key inspection items that require regular review.',
  '안전 조치 이력과 처리 상태를 확인하세요.': 'Review safety action history and processing status.',
  '현장에 필요한 안전 교육 콘텐츠와 이수 현황을 확인하세요.': 'Review safety training content and completion status for the site.',
  '대상자별 교육 이수 현황을 관리하고 현장 교육 자료를 생성하세요.': 'Manage completion by audience and create site training materials.',
  '조치 이력을 바탕으로 현장 위험도를 확인하고 관리하세요.': 'Review and manage site risk levels based on action history.',
  '회사의 안전보건 방침, 위험성 평가 조직, 허용가능 위험도를 관리하세요.': 'Manage safety policy, risk-assessment organization, and acceptable risk levels.',
  '보고서를 생성하고 생성된 보고서 목록을 확인하세요.': 'Create reports and review generated reports.',
  '관리자 정보와 계정 설정을 관리하세요.': 'Manage administrator information and account settings.',
  'AI 비서에게 점검·조치 및 교육 현황을 물어보세요.': 'Ask the AI Assistant about inspection, action, and training status.',
  '현장에서 접수된 위험 신고와 조치 진행 상태를 확인하세요.': 'Review risk reports from the field and their action status.',
  '개인정보 처리방침': 'Privacy Policy', '이용약관': 'Terms of Service', '뒤로 가기': 'Back', '시행일': 'Effective date',
  '대상': 'Audience', '이수율': 'Completion rate', '서버 집계': 'Server summary', '집계 중': 'Calculating',
  '새 교육이 배정되었습니다.': 'New training has been assigned.', '교육 관리에서 등록한': 'Please review', '을 확인해 보세요.': '.', '지금 보기': 'View now',
  '교육 영상': 'Training video', '안전 교육': 'Safety training', '교육 영상 미리보기': 'Training video preview',
  '재생 버튼을 눌러 교육을 시작하세요': 'Press play to begin training.', '재생 시간': 'Duration', '진행률': 'Progress',
  '영상의 80% 이상을 수강하면 자동으로 이수가 완료됩니다.': 'Completion is recorded automatically after watching 80% of the video.',
  '이전 강의': 'Previous course', '다음 강의': 'Next course', '나의 수강 현황': 'My learning overview', '구분': 'Type',
  '총': 'Total', '개 과정': ' courses', '이전 교육 목록': 'Previous course list', '다음 교육 목록': 'Next course list',
  '나의 학습 현황': 'My learning progress', '학습 안내': 'Learning guide', '수강 전 확인하세요': 'Before you begin',
  '영상의 80% 이상을 시청하면 자동으로 이수가 완료됩니다.': 'Completion is recorded automatically after watching 80% of the video.',
  '이수 여부에 상관없이 [다음 강의] 버튼을 눌러 목록을 순회할 수 있습니다.': 'You can browse the list with the [Next course] button at any time.',
  '타임라인 건너뛰기는 제한되며, 중간에 벗어나도 마지막 시청 위치가 자동 저장됩니다.': 'Skipping ahead is limited, and your last viewing position is saved automatically.',
  '교육 목록': 'course list', '내 교육 현황': 'My learning status', '교육 목록 창 닫기': 'Close course list',
  '현재 내 교육 리스트 기준': 'Based on your current learning list', '마감': 'Due', '해당하는 교육이 없습니다.': 'There are no matching courses.',
  '추천 질문': 'Suggested questions', '자주 확인하는 안전관리 현황입니다.': 'Frequently checked safety-management information.',
  '현재 조치 대기와 조치 완료 건수를 알려줘': 'Show pending and completed action counts.',
  '이번 달 점검 이력을 상태별로 알려줘': 'Show this month’s inspection history by status.',
  '우리 회사 전체 교육 현황과 이수율을 알려줘': 'Show our company’s training status and completion rate.',
  '미이수 교육 현황을 과정별로 알려줘': 'Show incomplete training by course.',
  'BOSS AI 비서': 'BOSS AI Assistant', '점검·조치 및 교육 현황을 확인하세요.': 'Review inspection, action, and training status.',
  '안녕하세요. BOSS AI 비서입니다. 무엇을 확인해 드릴까요?': 'Hello, I am the BOSS AI Assistant. What would you like to check?',
  '확인할 안전관리 현황을 입력하세요.': 'Enter the safety status you want to check.', '새 대화': 'New conversation', '질문 전송': 'Send question',
}

export const enFlat = Object.assign({}, ...Object.values(en), shared)

// Static labels that are rendered by legacy screens without calling t() yet.
// API/user-entered values intentionally do not belong in this map.
Object.assign(enFlat, {
  '이벤트 상세': 'Event details',
  '선택한 감지 결과를 확인합니다.': 'Review the selected detection result.',
  '감지 위치': 'Detection location',
  '감지 시간': 'Detection time',
  '신뢰도': 'Confidence',
  '담당자 배정': 'Assign staff',
  '알림': 'Notifications',
  '모두 읽음': 'Mark all as read',
  '모두 삭제': 'Delete all',
  '알림이 없습니다.': 'There are no notifications.',
  // Education management
  '교육 영상 등록': 'Training video registration', '교육 영상 추가': 'Add training video', '교육 영상 생성': 'Generate training video',
  '영상을 등록하면 선택한 대상자의 교육 목록에 즉시 표시됩니다.': 'The video will appear immediately in the selected audience\'s training list.',
  '교육명': 'Course name', '예: 3분기 지게차 안전교육': 'e.g. Q3 forklift safety training', '이수 대상': 'Audience', '세부 카테고리': 'Detailed category', '이수 유형': 'Training type', '마감일': 'Due date',
  '영상 등록 방식': 'Video registration method', '파일 첨부': 'Attach file', 'URL 입력': 'Enter URL', '교육 영상 파일을 선택하세요': 'Select a training video file', 'MP4, MOV, WebM 등 영상 파일': 'Video files such as MP4, MOV, and WebM', '변경': 'Change', '찾아보기': 'Browse', '영상 URL': 'Video URL', '교육 리스트에 추가': 'Add to training list',
  '교육 자료를 업로드하면 핵심 내용을 분석해 교육용 영상 초안을 만듭니다.': 'Upload training materials to analyze key points and create a training-video draft.', '교육 마감일': 'Training due date', '사용 장비': 'Equipment used', '위험 요인': 'Risk factors', '요청 사항': 'Request',
  '예: 창고 화재 예방 안전 교육': 'e.g. Warehouse fire-prevention safety training', '예: 지게차, 안전모, 절단기': 'e.g. Forklift, safety helmet, cutter', '예: 충돌, 낙하, 끼임': 'e.g. Collision, falling, caught-in hazards',
  '예: 지게차 운전자의 시점으로, 보호구 착용을 강조해 주세요.': 'e.g. Emphasize protective equipment from a forklift driver\'s perspective.', '교육 자료 업로드': 'Upload training materials', '원본은 서버에 저장하지 않습니다': 'Original files are not stored on the server', 'AI 교육 영상 생성': 'Generate AI training video',
  '교육 목록에 등록되었습니다.': 'Added to the training list.', '교육 관리와 내 교육 리스트에서 확인할 수 있습니다.': 'You can find it in Education Management and My Learning.', '교육명, 사용 장비, 위험 요인, 교육 마감일을 입력해 주세요.': 'Enter the course name, equipment, risk factors, and due date.',
  '생성된 교육 영상 검토': 'Review generated training video', '생성 결과 검토': 'Review result', '등록 전 영상을 확인해 주세요': 'Review the video before publishing.', '주의': 'Warning', 'AI 영상 품질 점수가': 'The AI video quality score is', '입니다. 기준 미달로 등록 전 검수가 필요합니다.': '. It is below the required threshold and must be reviewed before publishing.', '생성된 교육 영상 미리보기': 'Generated training video preview', '재생성 요청 사항': 'Regeneration request', '수정하고 싶은 장면, 강조할 내용, 말투 등을 입력해 주세요.': 'Enter scenes, points of emphasis, or tone you want to change.', '영상 재생성': 'Regenerate video', '취소하는 중...': 'Cancelling...', '등록 취소': 'Cancel registration', '등록 중...': 'Publishing...', '교육 목록에 등록 ▶': 'Add to training list ▶', '교육 영상을 재생성하고 있습니다': 'Regenerating training video', 'AI 교육 영상을 생성하고 있습니다': 'Generating AI training video', '자료를 분석하고 장면을 제작 중입니다.': 'Analyzing materials and creating scenes.',
  '교육 영상 추가 방식': 'Training video action', '등록': 'Register', '생성': 'Generate', '이름 또는 부서 검색': 'Search by name or department', '대상자': 'Audience member', '소속': 'Department', '이수 상태': 'Completion status', '이수 일시': 'Completion date', '조건에 맞는 대상자가 없습니다.': 'No audience members match the selected conditions.',
  '교육 대상자 현황': 'Training audience status', '전체 이수': 'Fully completed', '진도': 'Progress', '최근 이수일': 'Latest completion', '상세 창 닫기': 'Close details',
  '이수 현황을 확인하고 대상자를 검색할 수 있습니다.': 'Review completion status and search audience members.', '삭제할 교육 ID를 찾을 수 없습니다.': 'Unable to find the course ID to delete.', '교육을 정말 삭제하시겠습니까?': 'Are you sure you want to delete this course?', '모든 대상자의 이수 기록도 함께 삭제됩니다.': 'Completion records for all audience members will also be deleted.', '교육 삭제': 'Delete course',
  '교육 영상 생성 탭': 'Generate',
  // Board and history modals
  '위험 신고': 'Risk report', '게시글 작성': 'Create report', '신고 제목을 입력하세요': 'Enter a report title', '예: A동 2층 복도': 'e.g. Building A, 2nd-floor corridor', '위험 상황을 자세히 입력하세요': 'Describe the hazardous situation in detail',
  '사진': 'Photo', '신고 사진 미리보기': 'Risk report photo preview', '사진 삭제': 'Delete photo', '신고 상세': 'Report details', '신고 내용': 'Report details', '신고 사진': 'Report photo',
  '조치내용 등록': 'Add action details', '대상 신고': 'Related report', '조치내용을 입력해 주세요.': 'Enter the action details.', '완료한 조치 내용, 확인 결과, 후속 관리 사항을 입력하세요': 'Enter the completed action, verification result, and any follow-up required.',
  '위험요인 선택': 'Select a risk factor', '확인': 'Confirm',
  '완료된 점검의 담당자 메모를 확인합니다.': 'Review the inspector memo for this completed inspection.', '입력된 점검 메모가 없습니다.': 'No inspection memo was entered.',
  '완료된 조치 항목의 상세 정보를 확인합니다.': 'Review the details of this completed action.', '조치 등록 사진': 'Action registration photo', '감지/등록 당시의 최초 위험 현장 사진': 'Initial risk-site photo at detection or registration', '등록된 현장 사진 확인': 'Review the registered site photo',
  '반려됨': 'Rejected', '안전 상태 복구가 확인되었습니다.': 'The site has been confirmed safe.', '위험 요소가 완전히 해소되지 않았을 수 있습니다.': 'The risk may not have been fully resolved.', 'AI 검증 진행 중 / 미실행': 'AI verification in progress / not run', '안내': 'Information', '백그라운드에서 AI 검증이 처리 중이거나 아직 진행되지 않았습니다.': 'AI verification is running in the background or has not started yet.', '입력된 내용이 없습니다.': 'No details were entered.',
  '교육 관리 데이터를 불러오지 못해 기존 화면 데이터를 표시합니다.': 'Unable to load education-management data. Showing the existing screen data instead.',
  '검토 대기 중인 AI 교육 영상을 복원했습니다.': 'Restored an AI training video awaiting review.', '진행 중인 AI 교육 영상 생성을 다시 확인합니다.': 'Checking the AI training video generation already in progress.',
  '품질 기준 미달 영상입니다. 검수 후 등록하거나 추가 요청으로 재생성해 주세요.': 'This video is below the quality threshold. Review and publish it, or submit another request to regenerate it.', '품질 검수를 통과해 교육 목록에 자동 등록되었습니다.': 'The video passed quality review and was automatically added to the training list.',
  'AI 교육 영상 생성에 실패했습니다.': 'Failed to generate the AI training video.', '교육명, 마감일, 교육 영상을 모두 입력해 주세요.': 'Enter the course name, due date, and training video.', '교육 영상이 등록되었습니다.': 'The training video has been registered.', '교육 영상 등록에 실패했습니다.': 'Failed to register the training video.',
  'AI 교육 영상 생성을 시작했습니다. 완료되면 교육 목록에 자동으로 반영됩니다.': 'AI training video generation has started. It will be added to the training list automatically when complete.', 'AI 교육 자료 생성에 실패했습니다.': 'Failed to generate the AI training materials.',
  '교육 목록에 등록하려면 마감일을 지정해 주세요.': 'Set a due date before adding the video to the training list.', 'AI 품질 검수를 통과해 교육 목록에 자동 등록되었습니다.': 'The video passed AI quality review and was automatically added to the training list.', '검토한 AI 교육 영상이 교육 목록에 등록되었습니다.': 'The reviewed AI training video has been added to the training list.', '교육 목록 등록에 실패했습니다. 다시 시도해 주세요.': 'Failed to add the video to the training list. Please try again.', '등록 전 검수를 취소했습니다.': 'The pre-publication review has been cancelled.',
  '소방안전': 'Fire safety', '시설안전': 'Facility safety', '산업안전': 'Industrial safety', '기타': 'Other', '비율': 'Ratio',
  '카테고리': 'Category', '위험도': 'Risk level', '위험도 전체': 'All risk levels', '신고일 기간': 'Reported date range', '제목, 내용, 장소 검색': 'Search title, content, or location', '높음': 'High', '보통': 'Medium', '낮음': 'Low',
  '마이페이지': 'My Page', '안전관리자': 'Safety manager', '소방안전 관리자': 'Fire safety manager', '내 정보를 불러오는 중…': 'Loading your information…', '사용자 정보를 불러오지 못했습니다. 로그인 상태를 확인해 주세요.': 'Unable to load user information. Please check your login status.',
  '안전 관리 설정': 'Safety management settings', '회사 코드': 'Company code', '회사 코드 메뉴': 'Company code menu', '코드 생성': 'Generate', '내역': 'History', '역할': 'Role', '선택': 'Select', '생성 이후 표시됩니다': 'Shown after generation', '생성 완료': 'Generated', '생성 중': 'Generating', '완료': 'Complete', '삭제': 'Delete', '추가': 'Add', '전체 역할': 'All roles', '전체 상태': 'All statuses', '역할 필터': 'Role filter', '상태 필터': 'Status filter', '상태': 'Status', '생성일': 'Created on', '사용 완료': 'Used', '미사용': 'Unused', '근무자 역할': 'Worker roles', '유저 리스트 및 카테고리 변경': 'User list and category management', '변경 완료': 'Finish editing', '역할/카테고리 변경': 'Edit role/category', '이름': 'Name', '유저카테고리': 'User category', '일반유저': 'General user', '미지정': 'Unassigned',
  '조건에 맞는 회사 코드가 없습니다.': 'No company codes match the selected conditions.', '조건에 맞는 근무자가 없습니다.': 'No workers match the selected conditions.',
  '권한을 확인하고 있습니다.': 'Checking permissions.', '안전관리자만 회사 코드와 사용자 역할을 관리할 수 있습니다.': 'Only safety managers can manage company codes and user roles.', '안전관리 설정을 불러오지 못했습니다.': 'Unable to load safety-management settings.',
  '교육 현황': 'Training overview', '교육 이수 현황': 'Learning progress', '이수율': 'Completion rate', '선택 대상': 'Selected audience', '대상 교육': 'Assigned courses', '개 과정': ' courses', '대상자별 교육 리스트': 'Training list by audience', '교육 대상자': 'Training audience', '총': 'Total', '교육명 검색': 'Search course name', '교육 대상 필터': 'Training audience filter', '대상': 'Audience', '이수 완료': 'Completed', '상태': 'Status', '최근 등록순': 'Most recently added', '개 표시': ' shown', '이전 교육 목록': 'Previous training list', '다음 교육 목록': 'Next training list',
  '이수': 'Completed', '미이수': 'Not completed', '진행 중': 'In progress', '대기': 'Pending', '필수': 'Required', '정기': 'Recurring', '공통': 'Common', '안전관리자': 'Safety manager', '관제사': 'Control room operator', '현장관리자': 'Field manager', '일반유저': 'General user', '전체': 'All', '전체 임직원': 'All employees', '신규 근로자': 'New workers', '일반 작업자': 'General workers', '특수 작업자': 'Specialized workers', '안전 관리자': 'Safety managers', '지게차': 'Forklift', '화물트럭': 'Cargo truck', '토잉카': 'Tow truck', '팔레트': 'Pallet', '적재': 'Loading', '현장보조': 'Site support', '유지보수': 'Maintenance', '재고': 'Inventory', '위험물': 'Hazardous materials',
  // Reports
  '보고서': 'Reports', '보고서 생성': 'Generate report', '위험성평가표': 'Risk assessment form', '위험성평가 보고서': 'Risk assessment report', '경영책임자 검토지시서': 'Management review order', '종사자에 의한 유해 위험요인 보고서': 'Worker hazard report',
  '위험성평가표는 매일 자동으로 생성됩니다.': 'The risk assessment form is generated automatically every day.', '보고서 유형': 'Report type', '작성 기간': 'Reporting period', '시작일': 'Start date', '종료일': 'End date', '생성자': 'Created by', '계정 정보를 불러오는 중입니다': 'Loading account information',
  '보고서 생성에는 약 1~10분이 소요될 수 있습니다.': 'Generating a report may take about 1–10 minutes.', '생성 중...': 'Generating...', '리포트 생성': 'Generate report', '보고서 목록': 'Report archive', '보고서 항목을 선택하면 문서 미리보기를 확인할 수 있습니다.': 'Select a report to view its document preview.', '건': ' items', '제목': 'Title', '기간': 'Period', '다운로드': 'Download', '생성': 'Created', '보관': 'Retained until', '조건에 맞는 보고서가 없습니다.': 'No reports match the selected conditions.', '보고서 목록 페이지 이동': 'Report archive pagination', '페이지': 'Page', '이전': 'Previous', '다음': 'Next', '보고서 필터': 'Report filters', '제목 검색': 'Search title', '보고서 제목 검색': 'Search report title', '생성자 검색': 'Search creator', '초기화': 'Reset',
  '보고서 미리보기': 'Report preview', '보고서 문서 미리보기': 'Report document preview', '목록으로': 'Back to list', '문서를 불러오는 중입니다.': 'Loading document.', '이 보고서에는 연결된 Word 파일이 없습니다.': 'This report has no linked Word file.', 'Word 파일 미리보기를 표시하지 못했습니다.': 'Unable to display the Word file preview.',
  '유형 선택': 'Select type', '예: 화재': 'Example: Fire',
  '조치 이름': 'Action name', '조치 내용': 'Action details', '분류': 'Category', '취소': 'Cancel', '등록': 'Register', '등록 중...': 'Registering...', '등록 중입니다.': 'Registering item.',
  '점검 대기 상태로 등록됩니다.': 'The item will be registered as inspection pending.', '조치 대기 상태로 등록됩니다.': 'The item will be registered as action pending.',
  '위험요인 목록이 없습니다.': 'No risk factors are available.', '위험요인 페이지': 'Risk factor pages',
  '예: 소화기 압력 게이지 교체': 'Example: Replace extinguisher pressure gauge', '조치 시 확인할 기준이나 내용을 입력하세요': 'Enter the action criteria or details.',
  '전기안전': 'Electrical safety', '작업환경': 'Work environment',
  '화재 감지': 'Fire detection', '적재물': 'Stored materials', '충돌': 'Collision', '무단 침입': 'Unauthorized entry',
  '점검 항목 추가': 'Add inspection item', '조치 항목 추가': 'Add action item', '위험도 항목 추가': 'Add risk item',
  '전체 체크리스트에 새 항목을 등록합니다.': 'Add a new item to all checklists.', '위험요인': 'Risk factor', '점검 이름': 'Inspection name', '점검 내용': 'Inspection details',
  '적용 구역': 'Areas', '일시': 'Date and time', '이전': 'Previous', '다음': 'Next',
  '예: 비상구 피난 통로 점검': 'Example: Emergency exit route inspection', '점검 시 확인할 기준이나 내용을 입력하세요': 'Enter the criteria or details to check.',
  '여러 구역은 쉼표(,)로 구분하세요': 'Separate multiple areas with commas.',
  '닫기': 'Close', '목록': 'List', '반려': 'Reject', '승인': 'Approve', '반려 사유': 'Rejection reason', '결과': 'Result', '신뢰도': 'Confidence', '분석 내용': 'Analysis',
  '조치 전 위험 사진': 'Risk photo before action', '조치 후 완료 사진': 'Completion photo after action', '작업자 조치 내용': 'Worker action details',
  '등록 당시의 최초 위험 현장 사진': 'Initial risk-site photo when reported', '작업자가 현장에서 새로 등록한 완료 사진': 'Completion photo newly registered on site by the worker',
  '등록된 사진이 없습니다.': 'No registered photo.', '등록된 조치 사진이 없습니다.': 'No registered action photo.',
  '반려 시 사유를 입력해주세요. (승인 시 입력 불필요)': 'Enter a reason when rejecting. (Not required when approving.)',
  '위험요소 미해소 (확인 필요)': 'Risk not resolved (review required)', '위험요소 해소': 'Risk resolved',
  'AI 서버 연결 안 됨': 'AI server unavailable', '비디오 로드 실패': 'Video failed to load', '실시간 스트림 연결 중...': 'Connecting to live stream...',
  '모니터링으로 돌아가기': 'Back to CCTV monitoring', '상세 모니터링': 'Monitoring details', '위치 미지정': 'Location not specified', '확인 필요': 'Review required',
  '실시간 영상': 'Live video', '연결 상태 정상': 'Connection normal', '실시간 스트리밍 중': 'Live streaming', '카메라 전환': 'Switch camera',
  '대': ' cameras', '카메라 상태': 'Camera status', '정상 연결': 'Connected', '신호와 녹화 상태가 정상입니다.': 'Signal and recording are operating normally.',
  '오늘 감지': 'Detected today', '확인이 필요한 이벤트 1건': '1 event needs review.', '적재물 과다 적재 감지': 'Excessive stored materials detected',
  '감지 시간': 'Detected at', '주의': 'Caution', '체크리스트 확인': 'View checklists',
  '공통': 'Common', '안전관리자': 'Safety manager', '관제사': 'Control room operator', '현장관리자': 'Field manager', '일반유저': 'General user',
  '교육 이수 현황 기준': 'Learning progress filter', '명': ' people',
  '조치 내역 관리자 승인': 'Action record approval', '위험 유형': 'Risk type', '담당자': 'Assignee', '조치완료 시간': 'Action completed at',
  'AI 재확인 결과': 'AI recheck result', '승인 완료': 'Approved', '승인 대기': 'Pending approval', '조치 필요 (반려)': 'Action required (rejected)', '승인 검토': 'Review approval',
  'AI 분석 시작 중...': 'Starting AI analysis...', '연결 중...': 'Connecting...', '점검 준비 중': 'Preparing inspection', '점검 결과': 'inspection result',
  '조치 필요': 'Action required', '정상': 'Normal', '최근 점검': 'Last inspection',
  '건': ' items', '개 항목': ' items', '점': ' pts', '회': ' times',
  '번호': 'No.', '점검 이름': 'Inspection name', '카테고리': 'Category', '내용': 'Details',
  '주기적으로 확인해야 할 핵심 안전 점검 항목입니다. 행을 선택하면 점검 주기를 변경할 수 있습니다.': 'View key inspection items that require regular review. Select a row to change its inspection cycle.',
  '조건에 맞는 점검 항목이 없습니다.': 'No inspection items match the selected conditions.',
  '매일': 'Daily', '매주': 'Weekly', '매월': 'Monthly',
  '소방안전': 'Fire safety', '시설안전': 'Facility safety', '산업안전': 'Industrial safety', '기타': 'Other',
  '전기안전': 'Electrical safety', '작업환경': 'Work environment',
  '전체 점검': 'Total inspections', '점검 완료 건수': 'Completed inspections',
  '전체 조치': 'Total actions', '조치 완료 건수': 'Completed actions',
  '현장 담당자가 조치 사진을 첨부해 완료한 건만 확인하고 승인합니다.': 'Review and approve completed actions with site photos attached.',
  '점검 상태': 'Inspection status', '조치 담당자': 'Action assignee', '조치 사진': 'Action photo',
  '승인 상태': 'Approval status', '승인자 / 승인 일시': 'Approver / approved at',
  '중 즉시 확인 대상': ' require immediate attention', '개수': 'Count', '위험 요인 관리 작업': 'Risk factor actions', '취소하기': 'Cancel',
  '유형별 위험도 분포': 'Risk distribution by type', '총 감지': 'Total detected',
  '상': 'High', '중': 'Medium', '하': 'Low', '조치 승인 요청': 'Action approval requests',
  '요청일': 'Requested on', '내용': 'Details', '담당관리자': 'Responsible manager', '상태': 'Status',
  '전체 항목': 'Total items', '평균 강도': 'Average severity', '총 빈도': 'Total frequency',
  '핵심 위험 요인': 'Key risk factors', '상 위험 항목': 'High-risk items', '최다 유형': 'Most common type',
  '위험 요인 유형 그래프': 'Risk factor chart', '위험 요인 리스트': 'Risk factor list',
  '위험 요인 편집': 'Edit risk factors', '항목 추가': 'Add item', '항목 제거': 'Remove item',
  '유형': 'Type', '항목': 'Item', '위험도': 'Risk level', '강도': 'Severity', '빈도': 'Frequency',
  'CCTV AI 감지 모니터링': 'CCTV AI Detection Monitoring',
  '현장 CCTV와 실시간 감지 상태를 확인하세요.': 'Monitor site CCTV and real-time detection status.',
  '온라인': 'Online', '감지 이벤트': 'Detection events', '실시간 CCTV': 'Live CCTV',
  '화재 테스트와 지게차·보행자 거리 테스트를 분석합니다.': 'Analyze fire tests and forklift–pedestrian distance tests.',
  '최근 감지 이벤트': 'Recent detection events',
  'CCTV 감지 이벤트와 연결된 조치 내역을 최근순으로 표시합니다.': 'Shows the latest actions linked to CCTV detection events.',
  '영상 로드 실패': 'Video failed to load', '소화설비 자동 점검': 'Fire equipment automatic inspection',
  '최근 점검 프레임의 AI 탐지 결과를 확인합니다.': 'Review AI detection results from recent inspection frames.',
  '10분 주기': 'Every 10 min', '연결 안 됨': 'Disconnected', 'AI 서버 연결 안 됨': 'AI server unavailable',
  'AI 서버를 시작하면 점검 프레임이 표시됩니다.': 'Inspection frames appear when the AI server starts.',
  '최근 점검 점검 준비 중': 'Preparing the latest inspection.',
  '점검 목록': 'Inspection list', '점검 이름 또는 구역 검색': 'Search inspection name or area',
  '전체 카테고리': 'All categories', '점검 주기': 'Inspection cycle', '적용 구역': 'Areas',
  '점검 완료 내역': 'Completed inspections', '조치 완료 내역': 'Completed actions',
  '현장 담당자가 점검을 완료한 것만 확인합니다.': 'Review inspections completed by site staff.',
  '완료 일시': 'Completed at', '점검 담당자': 'Inspector', '점검 사진': 'Inspection photo',
  '조회 기간': 'Period', '기간 설정': 'Period settings', '이번 달': 'This month', '지난달': 'Last month',
  '승인 리포트': 'Approval report', '리포트 관리': 'Report management',
  '현재 조회 결과를 기준으로 리포트를 생성합니다.': 'Generate a report from the current results.',
  '리포트 생성': 'Generate report', '다운로드': 'Download', '사진 없음': 'No photo',
  '점검': 'Inspection', '조치': 'Action', '전체': 'All',
  '등록된 CCTV와 AI 감지 결과를 확인합니다.': 'View registered CCTV feeds and AI detection results.',
  'AI 감지 새로고침': 'Refresh AI detection',
  '감지 이벤트가 없습니다.': 'No detection events are available.',
  '점검 기준과 적용 구역을 확인하세요.': 'Review the inspection criteria and areas.',
  '구역별 마지막 점검 이력': 'Latest inspection history by area',
  '점검 이력은 이력 관리 화면에서 확인할 수 있습니다.': 'View inspection history in History management.',
  '점검 주기를 변경하면 연결된 체크리스트 관리 항목에도 동일하게 반영됩니다.': 'Changing the cycle also updates linked checklist management items.',
  '점검 주기 변경에 실패했습니다.': 'Failed to change the inspection cycle.',
  '점검 항목이 성공적으로 삭제되었습니다.': 'Inspection item deleted successfully.',
  '점검 항목 삭제에 실패했습니다.': 'Failed to delete the inspection item.',
  '점검 항목을 삭제하시겠습니까?': 'Delete this inspection item?',
  '조치 이력 데이터를 불러오지 못했습니다. 로그인 상태를 확인하세요.': 'Could not load action history. Check your sign-in status.',
  '점검 이력 데이터를 불러오지 못했습니다. 로그인 상태를 확인하세요.': 'Could not load inspection history. Check your sign-in status.',
  '승인 처리가 완료되었습니다.': 'Approval completed.',
  '반려 사유를 입력해주세요.': 'Enter a reason for rejection.',
  '반려 처리가 완료되었습니다. 해당 항목이 현장 작업자 조치 리스트로 되돌아갑니다.': 'Rejection completed. The item has returned to the site worker action list.',
  '조치 이력': 'Action history', '조치 점검 선택': 'Choose action or inspection',
  '게시글 상태 변경에 실패했습니다. 다시 시도해 주세요.': 'Failed to update the post status. Please try again.',
  '정말 이 게시글을 삭제하시겠습니까?': 'Delete this post?',
  '게시글이 삭제되었습니다.': 'Post deleted.', '게시글 삭제에 실패했습니다.': 'Failed to delete the post.',
  '선택한 게시글이 삭제되었습니다.': 'Selected posts deleted.', '일부 게시글 삭제에 실패했습니다.': 'Some posts could not be deleted.',
  '위험 신고가 등록되었습니다.': 'Risk report submitted.',
  '담당자 배정에 실패했습니다.': 'Failed to assign the person in charge.',
  '필수 입력 항목을 입력해 주세요.': 'Fill in all required fields.',
  '같은 이름의 점검 항목이 이미 등록되어 있습니다.': 'An inspection item with the same name already exists.',
  '점검 이력 생성에 실패했습니다.': 'Failed to create inspection history.',
  '조치 항목 생성에 실패했습니다.': 'Failed to create the action item.',
  '점검 완료 또는 다음 정기 점검 생성에 실패했습니다.': 'Failed to complete the inspection or create the next scheduled inspection.',
  '담당자 배정으로 이동되었습니다. 담당자 배정 후 조치목록에 표시됩니다.': 'Moved to assignee assignment. It will appear in the action list after assignment.',
  '조치 등록에 실패했습니다.': 'Failed to register the action.',
  '조치내용을 입력해 주세요.': 'Enter the action details.', '조치 사진을 첨부해 주세요.': 'Attach an action photo.',
  '새로 첨부한 조치 완료 사진이 필요합니다.': 'Attach a new completion photo.',
  '조치가 정상적으로 완료되었습니다.': 'Action completed successfully.',
  '조치 완료 처리(DB 저장)에 실패했습니다.': 'Failed to save action completion.',
  '보고서 생성': 'Generate report', '보고서 이름을 입력하세요': 'Enter a report name',
  '시작일': 'Start date', '종료일': 'End date',
  '이전 교육 목록': 'Previous course list', '다음 교육 목록': 'Next course list',
  '교육 관리 데이터를 불러오는 중입니다': 'Loading training management data',
  '상세 모니터링 정보를 불러오는 중입니다': 'Loading monitoring details',
  'CCTV 모니터링으로 돌아가기': 'Back to CCTV monitoring',
  '사진 크게 보기 닫기': 'Close enlarged photo', '사진 추가': 'Add photo',
})

const notificationTitleTranslations = {
  '위험 신고 접수': 'Risk report received',
  '조치 완료': 'Action completed',
  '근로자 피드백 보고서 생성 완료': 'Worker feedback report completed',
  '점검 완료': 'Inspection completed',
  '점검 배정': 'Inspection assigned',
  '조치 배정': 'Action assigned',
  '승인 요청': 'Approval requested',
  '승인 완료': 'Approval completed',
  '교육 이수 완료': 'Training completed',
  '교육 알림': 'Training notification',
}

const notificationTextReplacements = [
  ['위험 신고 게시글이 등록되었습니다.', 'A risk report has been submitted.'],
  ['조치를 완료했습니다.', 'The action has been completed.'],
  ['근로자 피드백 개선 보고서 생성이 완료되었습니다.', 'The worker feedback improvement report has been generated.'],
  ['점검이 완료되었습니다.', 'The inspection has been completed.'],
  ['점검이 배정되었습니다.', 'An inspection has been assigned.'],
  ['조치가 배정되었습니다.', 'An action has been assigned.'],
  ['승인 요청이 등록되었습니다.', 'An approval request has been submitted.'],
  ['승인이 완료되었습니다.', 'Approval has been completed.'],
  ['교육을 이수했습니다.', 'Training has been completed.'],
]

export function translateNotificationText(value, language) {
  if (language !== 'en' || typeof value !== 'string') return value
  if (notificationTitleTranslations[value]) return notificationTitleTranslations[value]

  let translated = value
  for (const [korean, english] of notificationTextReplacements) translated = translated.replace(korean, english)
  return translated
    .replace(/(\d+)시간 전/g, '$1 hours ago')
    .replace(/(\d+)분 전/g, '$1 minutes ago')
    .replace(/(\d+)일 전/g, '$1 days ago')
    .replace('방금 전', 'Just now')
}
